require 'spec_helper'

# skip testing basics which are generated by rails

describe Album do
  # describe helps you partion your testing
  subject(:album) {build(:album)}

  describe 'validation' do
    # Don't use BEFORE. instead, declare the subject of your testing
    # subject(:album) {Album.new(name: 'OK Computer', img_url: 'OKComputer.com')}

    it 'requires a name' do
      expect(subject).to be_valid
      subject.name = nil
      expect(subject).to be_invalid
    end

    it 'requires an img_url' do
      expect(subject).to be_valid
      subject.img_url = nil
      expect(subject).to be_invalid
    end
  end  

  describe 'associations' do
    it 'knows owning users' do
      expect(subject).to respond_to(:users)
    end

    it 'has songs' do
      expect(subject).to respond_to(:songs)
    end

    it 'has artists' do 
      expect(subject).to respond_to(:artists)
    end
  end
end


